# Generated by Django 6.0.6 on 2026-06-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appuser_address_appuser_designation_appuser_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(blank=True, default='SYSTEM_EVENT', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.CharField(blank=True, default='127.0.0.1', max_length=45),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_name',
            field=models.CharField(blank=True, default='System', max_length=200),
        ),
    ]
