# Generated by Django 6.0.6 on 2026-06-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appuser_address_appuser_designation_appuser_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='raw_password',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
