# Generated by Django 6.0.6 on 2026-06-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appuser_raw_password_auditlog_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignation',
            name='reason',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='relieving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=20),
        ),
    ]
