# Generated by Django 6.0.6 on 2026-06-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('More Info Required', 'More Info Required')], default='Pending', max_length=20),
        ),
    ]
