# Generated by Django 6.0.6 on 2026-06-23 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assetauditlog_resignation_meeting_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id_code', models.CharField(blank=True, default='', max_length=50)),
                ('employee_name', models.CharField(blank=True, default='', max_length=200)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('exit_rating', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED', 'SUBMITTED')], default='DRAFT', max_length=20)),
                ('reason_for_resignation', models.TextField(blank=True, default='')),
                ('role_satisfaction', models.IntegerField(blank=True, null=True)),
                ('manager_relationship', models.IntegerField(blank=True, null=True)),
                ('career_growth', models.IntegerField(blank=True, null=True)),
                ('company_culture', models.IntegerField(blank=True, null=True)),
                ('adequate_training', models.CharField(blank=True, default='', max_length=50)),
                ('most_enjoyed', models.TextField(blank=True, default='')),
                ('suggested_improvements', models.TextField(blank=True, default='')),
                ('recommend_to_others', models.CharField(blank=True, default='', max_length=10)),
                ('consider_rejoining', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interviews', to=settings.AUTH_USER_MODEL)),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interviews', to='api.resignation')),
            ],
        ),
    ]
