# Generated by Django 6.0.6 on 2026-06-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_action_type_auditlog_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(default='Laptop', max_length=50)),
                ('status', models.CharField(default='Available', max_length=50)),
                ('assigned_to', models.CharField(blank=True, default='', max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.IntegerField(blank=True, null=True)),
                ('asset_tag', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('performed_by', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
    ]

