# Generated by Django 6.0.6 on 2026-06-23 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_asset_assetauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignation',
            name='meeting_schedule',
            field=models.CharField(default='Today, 2:00 PM', max_length=200),
        ),
        migrations.AddField(
            model_name='resignation',
            name='meeting_status',
            field=models.CharField(default='Scheduled', max_length=100),
        ),
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_schedule', models.CharField(max_length=200)),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='api.resignation')),
            ],
        ),
    ]
