# Generated by Django 6.0.6 on 2026-06-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_resignation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Awaiting Exit Interview', 'Awaiting Exit Interview'), ('Pending', 'Pending'), ('Pending HR Review', 'Pending HR Review'), ('Exit Interview Pending', 'Exit Interview Pending'), ('Exit Interview Submitted', 'Exit Interview Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('More Info Requested', 'More Info Requested')], default='Pending', max_length=30),
        ),
    ]
