# Generated by Django 6.0.6 on 2026-06-27 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_resignation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMasterEmployee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('joining_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company Master Employee',
                'verbose_name_plural': 'Company Master Employees',
                'db_table': 'company_master"."employees',
            },
        ),
        migrations.CreateModel(
            name='HRManagementStaffProfile',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'HR Staff Profile',
                'verbose_name_plural': 'HR Staff Profiles',
                'db_table': 'hr_management"."staff_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserDirectoryEmployeePersonal',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hire_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Employee Personal Profile',
                'verbose_name_plural': 'Employee Personal Profiles',
                'db_table': 'user_directory"."employee_personal',
            },
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Awaiting Exit Interview', 'Awaiting Exit Interview'), ('Pending', 'Pending'), ('Pending HR Review', 'Pending HR Review'), ('Exit Interview Pending', 'Exit Interview Pending'), ('Exit Interview Submitted', 'Exit Interview Submitted'), ('Awaiting Approval', 'Awaiting Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('More Info Requested', 'More Info Requested')], default='Pending', max_length=30),
        ),
    ]
