# Generated by Django 6.0.6 on 2026-06-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_companymasteremployee_hrmanagementstaffprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoiningDateAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.IntegerField()),
                ('action_type', models.CharField(max_length=100)),
                ('previous_value', models.DateField(blank=True, null=True)),
                ('new_value', models.DateField(blank=True, null=True)),
                ('actor', models.CharField(default='System', max_length=200)),
                ('sync_status', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('portal', models.CharField(max_length=50)),
                ('date_val', models.DateField()),
                ('retries', models.IntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
