# Generated by Django 6.0.6 on 2026-07-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appuser_raw_password'),
        ('api', '0010_joiningdateauditlog_syncqueue'),
    ]

    operations = [
    ]
