# Generated by Django 6.0.6 on 2026-07-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='raw_password',
        ),
    ]
