from django.urls import path
from .views import (
    login_view,
    UserListView,
    UserDetailView,
    UserProfileView,
    ResignationListCreateView,
    ResignationUpdateView,
    ResignationWithdrawView,
    ResignationFeedbackView,
    settings_view,
    AuditLogListCreateView,
    health_check,
    DashboardMetricsView,
    SystemHealthView,
    SystemHealthV1View,
    AdminAnalyticsSyncView,
    AdminAuditLogListView,
    admin_audit_logs_stream,
)

urlpatterns = [
    path('health/', health_check, name='health-check'),
    path('login/', login_view, name='login'),
    path('users/', UserListView.as_view(), name='user-list'),
    path('users/me/', UserProfileView.as_view(), name='user-profile'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('resignations/', ResignationListCreateView.as_view(), name='resignation-list'),
    path('resignations/<int:pk>/', ResignationUpdateView.as_view(), name='resignation-update'),
    path('resignations/<int:pk>/withdraw/', ResignationWithdrawView.as_view(), name='resignation-withdraw'),
    path('resignations/<int:pk>/feedback/', ResignationFeedbackView.as_view(), name='resignation-feedback'),
    path('settings/', settings_view, name='settings'),
    path('audit-logs/', AuditLogListCreateView.as_view(), name='audit-log-list'),
    path('dashboard/metrics/', DashboardMetricsView.as_view(), name='dashboard-metrics'),
    path('system/health/', SystemHealthView.as_view(), name='system-health'),
    path('v1/system-health/', SystemHealthV1View.as_view(), name='system-health-v1'),
    path('v1/admin/analytics/sync/', AdminAnalyticsSyncView.as_view(), name='admin-analytics-sync'),
    path('v1/admin/audit-logs/', AdminAuditLogListView.as_view(), name='admin-audit-logs'),
    path('v1/admin/audit-logs/stream/', admin_audit_logs_stream, name='admin-audit-logs-stream'),
]

